### ISSUE TITLE
Datapacks only overwrite existing files

### ISSUE THREAD

**Issue by Freshah** [LogicTechCorp/Reagenchant#11]
Hello! When I've been using OpenLoader for my custom reagent datapack, loading a new world seems to load my datapack, AND the default reagents.   For now I'll get around it by renaming my .json files to match the ones I removed.  But it may be something to look into?

Edit to include example:  If I wanted to make it so I only had 1 Reagent, I'd need a pile of blank files named like the defaults.

**Comment by LogicTechCorp** [comment]
Reagents are disabled similarly to how recipes and advancements are disabled. Your data pack needs to provide a file with the same name and contents, but the "enchantments" field needs to be empty. As an example, providing the following json in your data pack will disable the iron ingot reagent: `{
  "item": "minecraft:iron_ingot",
  "enchantments": []
}`. There is currently a bug that causes disabled reagents to still get loaded, but it'll be fixed in the next beta release. I will also be adding a "disable" sub-command to the "reagent" command to easily disable a reagent so that it will stay disabled when exporting your data pack with the "exportCurrentReagentPack" command.

**Comment by Freshah** [comment]
I'm realizing how silly my issue was.  That sub-command sounds handy.  I think this can be marked as solved.  Thanks for the response!  Loving the mod.
