### ISSUE TITLE
crash on startup after updating library ex

### ISSUE THREAD

**Issue by Biviho** [LogicTechCorp/Reagenchant#4]
i have updated library ex from 1.0.12 to 1.1.1 after the update to nether ex and the game started crashing on startup with this crash log

https://paste.dimdev.org/gofuweduxe.mccrash

i posted this issue here cause removing reagenchant solves the problem (also tested in a light environment with only nether ex, library ex and reagenchant ).

**Comment by LessThanBenji** [comment]
i'm experiencing the same issue. my crash log is the same as Biviho's (see comment above). after some testing, i can conclude that Reagenchant causes a crash on launch with any version of LibraryEx above and including v1.1.0 (v1.0.12 is the most recent version to still work). this is unfortunate because the latest versions of NetherEx require LibraryEx v1.1.0-v1.1.2, and therefore you currently can't have Reagenchant and NetherEx loaded in the same instance (unless you downgrade NetherEx to an older version and LibraryEx to v1.0.12 or below). this was all tested on Forge v14.23.5.2847, fyi.

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version.

**Comment by LessThanBenji** [comment]
> This issue has been fixed in the latest version.

awesome! thanks
